VIA_ENABLE         = yes
VIAL_ENABLE        = yes
VIALRGB_ENABLE     = yes
ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
RAW_ENABLE = yes

OS_DETECTION_ENABLE = yes

SRC += logic.c

CONSOLE_ENABLE = yes
